apiVersion: v1
kind: Service
metadata:
  name: todo-project-svc
spec:
  type: NodePort
  selector:
    app: todo-project # This is the app as declared in the deployment.
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 8080