apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes: # Define volume
        - name: shared-todo
          persistentVolumeClaim:
            claimName: todo-claim # name of the volume claim, this will be used in the deployment
      containers:
        - name: todo-app
          image: duysmartum/todo-app:latest
          imagePullPolicy: Always
          volumeMounts: # Mount volume
            - name: shared-todo
              mountPath: /usr/src/app/files
